version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/logs.db:/app/logs.db

  frontend:
    build: ./frontend
    depends_on:
      - backend
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # This is the only port open to the outside world now!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
