version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      # This saves your SQLite database to your actual hard drive 
      # so it doesn't get deleted when the container turns off
      - ./backend/logs.db:/app/logs.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
